pig dice 1step complate.
himchan94/pig_dice pull request #6
Opened 2021-11-25 11:42 UTC by Hyejic

resolve #4

2021-11-25 11:45 UTC, himchan94 commented on main.js
> +const randomNum = Math.floor(Math.random() * 7)
숫자 0이 나와요! 수정해주세요

2021-11-25 11:45 UTC, himchan94 requested changes
코멘트 확인해주세요~

2021-11-25 11:51 UTC, Hyejic commented on main.js
> +const randomNum = Math.floor(Math.random() * 7)
마지막 commit 소스에는 1~6까지 출력되도록 소스 수정되어있습니다!

2021-11-25 12:41 UTC, himchan94 approved these changes

2021-11-26 04:38 UTC, himchan94 approved these changes

2021-11-26 04:38 UTC, merged